//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// StViewer.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STATUS_FPS                  101
#define IDS_STATUS_PIXEL_INFO           102
#define IDS_STATUS_RECEIVED_IMAGE_COUNT 103
#define IDS_DEVICE_OPENED               104
#define IDS_DEVICE_CLOSED               105
#define IDS_STREAMING_STARTED           106
#define IDS_STREAMING_STOPPED           107
#define IDS_DEVICE_LOST                 108
#define IDS_TOOLBAR_ADVANCED            109
#define IDS_TOOLBAR_DRAWING             110
#define IDS_STRING_FFC_START            111
#define IDS_STRING_FFC_END_SUCCEEDED    112
#define IDS_FILE_OPENED                 113
#define IDS_FILE_CLOSED                 114
#define IDS_STRING_FILE_TIME            115
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CAMERA_CTRL                 130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDR_OUTPUT_POPUP                182
#define ID_SET_STYLE                    201
#define IDS_BUILD_TAB                   300
#define IDS_LOG_TAB                     300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_VIDEO_FILE           310
#define IDI_ICON1                       311
#define IDI_OUTPUT_WND                  316
#define IDI_OUTPUT_WND_HC               317
#define IDI_PROPERTIES_WND              318
#define IDI_PROPERTIES_WND_HC           319
#define IDR_MAINFRAME_HIDE              335
#define IDR_MAINFRAME_ADVANCED          335
#define IDR_TOOLBAR3                    337
#define IDR_MAINFRAME_HIDE256           337
#define IDR_MAINFRAME_ADVANCED256       337
#define IDD_DIALOG_CONFIGURATION_FILE   339
#define IDR_DEFECTIVE_PIXEL_DETECTION   353
#define IDR_DEFECTIVE_PIXEL_DETECTION_256 356
#define IDI_FILE_CTRL                   358
#define IDI_FILE_BMP_CTRL               359
#define IDR_TOOLBAR_DRAWING             360
#define IDI_FILE_BMP_CTRL2              360
#define IDI_FILE_PNG_CTRL               360
#define IDD_DIALOG_STILL_IMAGE_FILES    360
#define IDR_TOOLBAR_DRAWING_256         361
#define IDI_FILE_TIF_CTRL               361
#define IDI_FILE_TIFF_CTRL              362
#define IDR_XML1                        362
#define IDR_XML_STVIEWER                362
#define IDI_FILE_JPG_CTRL               363
#define IDI_FILE_JPEG_CTRL              364
#define IDW_UNUSED_ID_FIRST             1000
#define IDW_UNUSED_ID_LAST              2999
#define IDC_COMBO_FILE_FORMAT           3300
#define IDC_COMBO_CODEC                 3301
#define IDC_EDIT_MAXIMUM_FRAME_COUNT    3302
#define IDC_SPIN_MAXIMUM_FRAME_COUNT    3303
#define IDC_LIST_FILE_NAME              3305
#define IDC_BUTTON_ADD_FILE_NAME        3306
#define IDC_BUTTON_NODE_MAP             3307
#define IDC_STATIC_NODE_MAP             3308
#define IDC_STATIC_VERSION              3309
#define IDC_COMBO_CONFIG_FILE_DISPLAY_IMAGE_WINDOW 3310
#define IDC_COMBO_CONFIG_FILE_DEVICE_NODE_MAP_WINDOW 3311
#define IDC_COMBO_CONFIG_FILE_DEFECTIVE_PIXEL_DETECTION 3312
#define IDC_EDIT_STILL_IMAGE_FILES_PATH 3318
#define IDC_BUTTON_STILL_IMAGE_FILES_PATH 3319
#define IDC_EDIT_STILL_IMAGE_FILES_NAME_PATTERN 3320
#define IDC_EDIT_SAVE_IMAGE_FILE_COUNT  3321
#define IDC_EDIT_SAVE_A_IMAGE_PER       3322
#define IDC_STATIC_SAVE_AN_IMAGE_PER    3323
#define IDC_COMBO_FILE_TYPE             3324
#define IDC_BUTTON1                     3325
#define IDC_BUTTON_NODE_MAP_AREA        3325
#define IDC_COMBO_CONFIG_FILE_PIXEL_FORMAT_CONVERTER 3326
#define IDC_COMBO1                      3327
#define IDC_COMBO_CONFIG_FILE_STVIEWER  3327
#define ID_ACQ_START                    32771
#define ID_ACQ_STOP                     32772
#define ID_SAVE_STILL_IMAGE             32773
#define ID_SAVE_AVI                     32774
#define ID_STOP_RECORDING               32775
#define ID_START_RECORDING              32776
#define ID_FILE_SAVE_CAMERA_CONFIG_FILE 32777
#define ID_FILE_LOAD_CAMERA_CONFIG_FILE 32778
#define ID_FILE_SAVE_CAMERA_DESCRIPTION_FILE 32779
#define ID_WINDOW_TILE                  32782
#define ID_APPLICATIONLOOK_WINDOWS7     32789
#define ID_VIEW_INTERFACENODE           32825
#define ID_FILE_CONFIGURATIONFILESETTING 32828
#define ID_FILE_CONFIGURATIONFILESETTING32829 32829
#define ID_H_GRID_COUNT                 32840
#define ID_V_GRID_COUNT                 32841
#define ID_DRAWING_NONE                 32850
#define ID_DRAWING_SELECT               32851
#define ID_DRAWING_LINE                 32852
#define ID_DRAWING_RECTANGLE            32853
#define ID_DRAWING_ELLIPSE              32854
#define ID_DRAWING_TEXT                 32855
#define ID_DRAWING_ANGLE                32856
#define ID_DRAWING_POLYGON              32857
#define ID_DRAWING_PERPENDICULAR        32858
#define ID_DRAWING_ARC                  32859
#define ID_DRAWING_BEZIER               32860
#define ID_DRAWING_FREEHAND             32861
#define ID_DRAWING_CROSS                32862
#define ID_BUTTON32903                  32903
#define ID_WINDOW_FULLSCREEN            32904
#define ID_BUTTON32906                  32906
#define ID_FILE_STARTCALCULATINGFFCCORRECTIONVALUE 32907
#define ID_FILE_START_FFC               32908
#define ID_FILE_DEFECTIVEPIXELDETECTION 32909
#define ID_REGISTER_REGISTERSELECTEDPIXELS 32910
#define ID_REGISTER_DEREGISTERSELECTEDPIXELS 32911
#define ID_DETECTION_CLEARDETECTEDDEFECTIVEPIXELINFORMATION 32912
#define ID_BUTTON_DETECT_DEFECTIVE_PIXEL 32913
#define ID_BUTTON_CLEAR_DETECTED_PIXEL_INFO 32915
#define ID_BUTTON_REGSTER_DEFECTIVE_PIXEL 32918
#define ID_BUTTON_DEREGSTER_DEFECTIVE_PIXEL 32919
#define ID_BUTTON_GET_REGISTERED_PIXE_INFO 32922
#define ID_BUTTON_SAVE_AVERAGED_IMAGE   32924
#define ID_BUTTON_HIGHLIGHT_DEFECTIVE_PIXELS 32927
#define ID_BUTTON_PIXEL_CORRECTION_ENABLED 32928
#define ID_VIEW_GRAPHDATASOURCE         32930
#define ID_GRAPHDATASOURCE_REGISTEREDIMAGE 32931
#define ID_GRAPHDATASOURCE_CONVERTEDIMAGE 32932
#define ID_VIEW_SYSTEMNODE              32935
#define IDS_STRING_FFC_END_FAILED       61216

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        363
#define _APS_NEXT_COMMAND_VALUE         32936
#define _APS_NEXT_CONTROL_VALUE         3328
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
